### ISSUE TITLE
Better array support.

### ISSUE THREAD

**Issue by jordonbiondo** [queckezz/fmt-obj#2]
It would be great if the package descended into arrays and printed the formated output of each element rather than `.join`-ing their string representations. Ideally an array of objects would print the fully formatted value of each object indented further.

Consider the differences shown below.

Using `fmt-obj`: on `{asdf: [{a: 3, b: 4}, {x: 10}]}`

```json
  
    asdf: "[object Object],[object Object]"
```

Using the `prettyjson` library:

```yaml
asdf: 
  - 
    a: 3
    b: 4
  - 
    x: 10
```

**Comment by queckezz** [comment]
Thanks for the feedback. I just released `1.2.0` with better array support :sparkles:. Can you try it out and see what you think of it?

**example of how it looks now**
![image](https://cloud.githubusercontent.com/assets/2580598/23120737/d7a5397a-f75d-11e6-817d-580407968642.png)
