### ISSUE TITLE
Better Circular Reference Displays

### ISSUE THREAD

**Issue by jordonbiondo** [queckezz/fmt-obj#3]
Objects with circular references display `(collapsed)` on these references rather than displaying a representation of the circular relationship.

Consider using a library like `ciruclar-json` or something else to handle these cases.

Consider the following output below:

Using `fmt-obj` on an object with a circular reference:
Note that `object.b.z` points back to the root object, and `object.d` points to `.b.c.e`

```json
  
    a: 3
    b: 
       x: 10
       z: (collapsed)
       c: (collapsed)
    d: 
       foo: "bar"
```

Using `prettyjson` and `circular-json` together on the same object:

```yaml
a: 3
b: 
  x: 10
  z: ~
  c: 
    e: 
      foo: bar
d: ~b~c~e
```

**Comment by queckezz** [comment]
Added in `1.3.0` :sparkles: :
