### ISSUE TITLE
2 minor things

### ISSUE THREAD

**Issue by jd327** [queckezz/fmt-obj#6]
1. Shouldn't `readme` `customFormat` example contain `Infinity` as the 2nd param?

  ```javascript
  const customFormat = (...args) => format(...args, Infinity, {
    punctuation: chalk.cyan,
    annotation: chalk.red,
    property: chalk.yellow,
    literal: chalk.blue,
    number: chalk.green,
    string: chalk.bold
  })
  ```

2. If you don't provide one of the color properties, it throws this. Can you merge with the default object?

```shell
TypeError: formatter.punctuation is not a function
    at .../node_modules/fmt-obj/dist.js:82:114
```

**Comment by queckezz** [comment]
Yea I think the API was pretty flawed. If you want custom formatting you now have to import `createFormatter()`. It also now merges the default configuration so it shouldn't throw at you anymore.

```js
const { createFormatter } = require('fmt-obj')

const format = createFormatter({
  annotation: chalk.red.bold.italic.whatever
})
```
